image: node:latest

before_script:
  - npm install --global web-ext

submit_amo:
  stage: build
  only:
    - master
  allow_failure: true
  script:
    - web-ext sign --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --id=$AMO_ID
